#include <iostream>
#include <string>

using namespace std;

int main()
{
   string clsm1;
   cout << "classmate 1: ";
   getline(cin, clsm1, '\n');
   string clsm2;
   cout << "classmate 2: ";
   getline(cin, clsm2, '\n');
   string clsm3;
   cout << "classmate 3: ";
   getline(cin, clsm3, '\n');
   string clsm4;
   cout << "classmate 4: ";
   getline(cin, clsm4, '\n');
   string clsm5;
   cout << "classmate 5: ";
   getline(cin, clsm5, '\n');
   string clsm6;
   cout << "classmate 6: ";
   getline(cin, clsm6, '\n');
   string clsm7;
   cout << "classmate 7: ";
   getline(cin, clsm7, '\n');
   string clsm8;
   cout << "classmate 8: ";
   getline(cin, clsm8, '\n');
   string clsm9;
   cout << "classmate 9: ";
   getline(cin, clsm9, '\n');
   string clsm10;
   cout << "classmate 10: ";
   getline(cin, clsm10, '\n');
   string clsm11;
   cout << "classmate 11: ";
   getline(cin, clsm11, '\n');
   string clsm12;
   cout << "classmate 12: ";
   getline(cin, clsm12, '\n');
   string clsm13;
   cout << "classmate 13: ";
   getline(cin, clsm13, '\n');
   string clsm14;
   cout << "classmate 14: ";
   getline(cin, clsm14, '\n');
   string clsm15;
   cout << "classmate 15: ";
   getline(cin, clsm15, '\n');
   string clsm16;
   cout << "classmate 16: ";
   getline(cin, clsm16, '\n');
   string clsm17;
   cout << "classmate 17: ";
   getline(cin, clsm17, '\n');
   string clsm18;
   cout << "classmate 18: ";
   getline(cin, clsm18, '\n');
   string clsm19;
   cout << "classmate 19: ";
   getline(cin, clsm19, '\n');
   string clsm20;
   cout << "classmate 20: ";
   getline(cin, clsm20, '\n');
   cout << clsm1 << endl;
   cout << clsm2 << endl;
   cout << clsm3 << endl;
   cout << clsm4 << endl;
   cout << clsm5 << endl;
   cout << clsm6 << endl;
   cout << clsm7 << endl;
   cout << clsm8 << endl;
   cout << clsm9 << endl;
   cout << clsm10 << endl;
   cout << clsm11 << endl;
   cout << clsm12 << endl;
   cout << clsm13 << endl;
   cout << clsm14 << endl;
   cout << clsm15 << endl;
   cout << clsm16 << endl;
   cout << clsm17 << endl;
   cout << clsm18 << endl;
   cout << clsm19 << endl;
   cout << clsm20 << endl;
   return 0;
}
